export const editEvent = {
    redo: "redo",
    undo: "undo",

    focus: "focus",
    bold: "bold",
    italic: "italic",
    underline: "underline",
    strikeThrough: "strikeThrough",
    eraser: "eraser",
    color: "color",
    bgColor: "bgColor",
    fontSize: "fontSize",
    fontFamily: "fontFamily",
    lineHeight: "lineHeight",
    fontEffect: "fontEffect",
    toggleBlock: "toggleBlock",
    blockAlign: "blockAlign",
    wrapper: "wrapper",
    emoticon: "emoticon",
    addLink: "addLink",
    editLink: "editLink",
    openEditLink: "openEditLink",
    removeLink: "removeLink",
    addCode: "addCode",
    openEditCode: "openEditCode",
    editCode: "editCode",

    openEditFormula: "openEditFormula",
    addFormula: "addFormula",
    addInlineFormula: "addInlineFormula",
    editFormula: "editFormula",
    editInlineFormula: "editInlineFormula",

    addHorizontalRule: "addHorizontalRule",

    openEditImage: "openEditImage",
    addImage: "addImage",
    editImage: "editImage",
    addInlineImage: "addInlineImage",
    editInlineImage: "editInlineImage",

    openEditVideo: "openEditVideo",
    addVideo: "addVideo",
    editVideo: "editVideo",

    openEditAudio: "openEditAudio",
    addAudio: "addAudio",
    editAudio: "editAudio",

    openEditFile: "openEditFile",
    addFile: "addFile",
    editFile: "editFile",

    openEditIframe: "openEditIframe",
    addIframe: "addIframe",
    editIframe: "editIframe",

    openEditComment: "openEditComment",
    addComment: "addComment",
    editComment: "editComment",

    expandableList: "expandableList",
    editExpandableList: "editExpandableList",

    openEditTable: "openEditTable",
    addTable: "addTable",
    editTableAttr: "editTableAttr",
    editTableNum: "editTableNum",
};
